
# Default update config
# Config order: hparams_registry -> config.yaml -> CLI

swad: LossValley
swad_kwargs:
  n_converge: 3
  n_tolerance: 6
  tolerance_ratio: 1.5 #1.2
  #1.5
test_batchsize: 32  #1    #32 # 128
indomain_test: False  # use indomain test split or not


